# -*- coding: utf-8 -*-
"""ML3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TG3zEP_iW0kSvxKQU4M8nazeNm5T6vmE
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

df = pd.read_csv('/content/Admission_Predict.csv')

df.head()

df.shape

df.dtypes

df.columns

from sklearn.preprocessing import Binarizer

bi = Binarizer(threshold=0.75)
df['Chance of Admit '] = bi.fit_transform(df[['Chance of Admit ']])

df.head()

x = df.drop('Chance of Admit ', axis = 1)
y = df['Chance of Admit ']

y = y.astype('int')

y

x

sns.countplot(x = y)

y.value_counts()

# Cross Validation
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=0, train_size=0.75)

x_train.shape

x_test.shape

from sklearn.tree import DecisionTreeClassifier

classifier = DecisionTreeClassifier(random_state=0)

classifier.fit(x_train,y_train)

y_pred = classifier.predict(x_test)

from sklearn.metrics import ConfusionMatrixDisplay
from sklearn.metrics import classification_report

ConfusionMatrixDisplay.from_predictions(y_test,y_pred)

print(classification_report(y_test,y_pred))

from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

from sklearn.tree import plot_tree
import matplotlib.pyplot as plt

plt.figure(figsize=(18,9))
plot_tree(classifier, fontsize=8, filled=True,
          feature_names=x.columns, class_names=['NA', 'AD']);